### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Jak2k** [JJTech0130/kodobe#1]

**Comment by JJTech0130** [comment]
Unfortunately I never finished this project, so it cannot be installed in its current state.

**Comment by Jak2k** [comment]
That's unfortunate. What would need to be done to make it work?

**Comment by JJTech0130** [comment]
You're much better off using https://github.com/Leseratte10/acsm-calibre-plugin with Calibre on your PC, then transferring the resulting book to KOReader. I don't think I even fully implemented the ADEPT protocol yet?

**Comment by xrubioj** [comment]
> You're much better off using https://github.com/Leseratte10/acsm-calibre-plugin with Calibre on your PC, then transferring the resulting book to KOReader. I don't think I even fully implemented the ADEPT protocol yet?

I've stumbled upon this project while searching for how to use Adobe DRM with KOReader. I would suggest making it more visible by adding a note in the [README.md](../blob/master/README.md).

I've made a quick PR with a proposal, if you want to go ahead and merge it https://github.com/JJTech0130/kodobe/pull/2 .
